In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

import random
import xgboost
import shap
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn import svm, metrics
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV
import xgboost as xgb
from sklearn.metrics import mean_squared_error

In [2]:
def mean_absolute_percentage_error(y_pred, y_true): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

def rmse_percentage_error(y_pred, y_true):
    rmspe = np.sqrt(np.mean(np.square(((y_true - y_pred) / y_true)), axis=0))
    return rmspe * 100

# min max transform
def min_max_trsf(df:pd.DataFrame, esc_col=list()):
    cols = df.columns
    for col in cols:
        if col in esc_col:
            continue
        
        data = df[[col]].values
        
        scaler = preprocessing.MinMaxScaler()
        scaler.fit(data)
        trsf_val = scaler.fit_transform(data)
        
        df[col] = trsf_val
        
    
    return df

In [3]:
DATA = pd.read_csv('ABCD_FG_GENDER.csv')

In [4]:
DATA.head()

,id,ds,bmi-gt,gender,age,race,roll,yaw,pitch,fg_width,...,LFI,LFI2,BCI,BCI2,CFI,CFI2,CFI3,CFI4,CFI5,CFI6
0,248038.jpg,A,39.051673,Male,NaN,NaN,-1.044744,0.657012,-17.841677,277,...,0.016598,0.000611,0.041407,24.150452,0.002026,0.001878,0.318108,0.159054,0.294829,0.147414
1,250464.jpg,A,29.288755,Male,NaN,NaN,6.014569,-1.300598,-17.101769,221,...,0.022372,0.001292,0.067288,14.861461,0.002462,0.002462,0.217171,0.108585,0.217192,0.108596
2,263711.jpg,A,42.825074,Male,NaN,NaN,4.821493,4.867723,-14.034566,283,...,0.017967,0.000807,0.057071,17.521985,0.002250,0.002207,0.290540,0.145270,0.284959,0.142479
3,270020.jpg,A,23.028230,Male,NaN,NaN,0.003432,-0.031101,-18.438297,206,...,0.025274,0.001407,0.067574,14.798681,0.003173,0.002797,0.317598,0.158799,0.279941,0.139971
4,277774.jpg,A,29.529949,Male,NaN,NaN,7.127036,7.221483,-17.001773,293,...,0.018155,0.000751,0.052017,19.224349,0.002312,0.002043,0.314634,0.157317,0.278101,0.139050

In [5]:
BMIFEAT = [
    'CJWR', 'CJWR2',
          'FMWR', 'FMWR2',
          'ESR', 'ESR2', 'ESR3', 'ESR4',
          'EBHR', 'EBHR2', 'EBHR3', 'EBHR4', 'EBHR5',
          'TR', 'TR2', 'TR3', 'TR4',
          'ITR', 'ITR2', 'ITR3', 'ITR4',
          'FCR', 'FCR2', 'FCR3', 'FCR4', 'FCR5',
          'UCR', 'UCR2', 'UCR3', 'UCR4', 'UCR5',
          'TA', 'TA2', 'TA3', 'TA4',
          'ITA', 'ITA2', 'ITA3', 'ITA4',
          'FCA', 'FCA2', 'FCA3', 'FCA4',
          'UCA', 'UCA2', 'UCA3', 'UCA4',
          'FTZA', 'FTZA2',
          'FPYA', 'FPYA2',
          'CFA', 'CFA2',
          'LFI', 'LFI2',
          'BCI', 'BCI2',
          'CFI', 'CFI2', 'CFI3', 'CFI4', 'CFI5', 'CFI6'
          ]

ALLFEAT = BMIFEAT
print('目前所有特徵數量: {}'.format(len(ALLFEAT)))

目前所有特徵數量: 63